module.exports = [
  'New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 
  'San Diego', 'Dallas', 'San Jose', 'Austin', 'Jacksonville', 'Fort Worth', 'Columbus', 
  'Charlotte', 'San Francisco', 'Indianapolis', 'Seattle', 'Denver', 'Washington',
  'In your room', 'Heaven', 'Hell', 'Upstairs', 'Downstairs', 'The Moon', 'Mars', 'Atlantis', 
  'Narnia', 'Hogwarts', 'Middle Earth', 'Gotham City', 'Metropolis', 'Springfield', 
  'Bikini Bottom', 'Pawnee', 'Wakanda', 'Emerald City', 'The Shire', 'Winterfell', 
  'King\'s Landing', 'Panem', 'The Death Star', 'Camelot', 'El Dorado', 'Neverland', 
  'Rivendell', 'The Underworld', 'The Upside Down', 'Jurassic Park', 'Mystic Falls', 
  'Silent Hill', 'Stars Hollow', 'Sunnydale', 'Krypton', 'Bedrock', 'Pemberley', 'Baker Street', 
  'Shangri-La', 'Zion', 'Kanto Region', 'Hyrule', 'The Matrix', 'Pandora', 'Westworld', 
  'San Junipero', 'Black Mirror', 'Stargate Command', 'Cybertron', 'Asgard', 'Valhalla', 
  'The Citadel', 'Helm\'s Deep', 'The Triskelion', 'Cloud City', 'Mos Eisley', 'The Red Keep', 
  'The Wall', 'Winterhold', 'High Hrothgar', 'Solitude', 'Whiterun', 'Riverwood', 
  'White House', 'The Pentagon', 'Area 51', 'Vatican City', 'Buckingham Palace', 'Taj Mahal', 
  'Eiffel Tower', 'Great Wall of China', 'Pyramids of Giza', 'Machu Picchu', 'Sydney Opera House', 
  'Stonehenge', 'Mount Everest', 'Sahara Desert', 'Amazon Rainforest', 'The Arctic Circle', 
  'Antarctica', 'The Bermuda Triangle', 'The Mariana Trench', 'The International Space Station',
  'Atlantis', 'Chernobyl', 'Oz', 'Westeros', 'Starfleet Academy', 'Mordor', 'Tatooine', 'Arendelle',
  'Skyrim', 'Azeroth', 'Coruscant', 'Rapture', 'Yavin IV', 'Naboo', 'Dune', 'Arrakis', 'Gondor', 
  'Endor', 'Hoth', 'Star City', 'Central City', 'Duckburg', 'Sherwood Forest', 'Themyscira', 
  'Westeros', 'Duckburg', 'Mooseport', 'Riverdale', 'Pallet Town', 'Pallet Town', 'Route 66', 
  'South Pole', 'North Pole', 'Shire', 'Isengard', 'Lothlórien', 'Mirkwood', 'Lothlórien', 'Roanapur',
  'Green Gables', 'Secret Annex', 'Chocolate Factory', 'Monsteropolis', 'Unseen University', 
  'Smurf Village', 'St. Olaf', 'Hill Valley', 'Vulcan', 'Kronos', 'Bajor', 'Ferenginar', 'Sanctuary', 
  'Transylvania', 'Barsoom', 'Perelandra', 'Lancre', 'Florin', 'Guilder', 'Gormenghast', 
  'Tanelorn', 'Stormwind', 'Dalaran', 'Ironforge', 'Darnassus', 'Orgrimmar', 'Thunder Bluff', 
  'Silvermoon', 'Undercity', 'Shattrath', 'Dalaran'
];
