module.exports = [
  'Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy', 
  'Karen', 'Leo', 'Mallory', 'Nina', 'Oscar', 'Peggy', 'Quincy', 'Ruth', 'Steve', 'Trent',
  'Ursula', 'Victor', 'Wendy', 'Xander', 'Yara', 'Zane',
  'I am king', 'King Kong', 'I am Elon', 'Charger', 'Batman', 'Superman', 'Wonder Woman', 'Spiderman',
  'Iron Man', 'Thor', 'Hulk', 'Captain America', 'Black Widow', 'Hawkeye', 'Loki', 'Doctor Strange',
  'Star-Lord', 'Groot', 'Rocket', 'Gamora', 'Drax', 'Ant-Man', 'Wasp', 'Black Panther', 'Shuri',
  'Thanos', 'Wolverine', 'Deadpool', 'Professor X', 'Magneto', 'Storm', 'Cyclops', 'Jean Grey',
  'Nightcrawler', 'Mystique', 'Rogue', 'Gambit', 'Colossus', 'Beast', 'Silver Surfer', 'Daredevil',
  'Punisher', 'Blade', 'Ghost Rider', 'Iron Fist', 'Luke Cage', 'Jessica Jones', 'The Flash', 'Green Lantern',
  'Aquaman', 'Martian Manhunter', 'Cyborg', 'Green Arrow', 'Hawkgirl', 'Shazam', 'Catwoman', 'Joker',
  'Harley Quinn', 'Poison Ivy', 'Penguin', 'Riddler', 'Two-Face', 'Mr. Freeze', 'Bane', 'Scarecrow',
  'Ra`s al Ghul', 'Darkseid', 'Brainiac', 'Lex Luthor', 'Zod', 'Doomsday', 'Ivy', 'Neo', 'Morpheus',
  'Trinity', 'Agent Smith', 'Voldemort', 'Harry Potter', 'Hermione', 'Ron Weasley', 'Dumbledore',
  'Snape', 'Hagrid', 'Sirius Black', 'Lupin', 'Bellatrix', 'Draco', 'Luna Lovegood', 'Neville Longbottom',
  'Ginny Weasley', 'Fred Weasley', 'George Weasley', 'Percy Weasley', 'Dobby', 'Kreacher', 'Grindelwald',
  'Newt Scamander', 'Jacob Kowalski', 'Tina Goldstein', 'Queenie Goldstein', 'Nagini', 'I am Groot', 
  'SpongeBob', 'Patrick', 'Squidward', 'Mr. Krabs', 'Sandy Cheeks', 'Plankton', 'Gary', 'Larry the Lobster', 
  'Mrs. Puff', 'Mermaid Man', 'Barnacle Boy', 'King Neptune', 'Perch Perkins', 'Man Ray', 'Dirty Bubble',
  'Flying Dutchman', 'Karen Plankton', 'Old Man Jenkins', 'Bubble Bass', 'Hans', 'Fred', 'The Tickler', 
  'Mini Timmy', 'Poppy Puff', 'Rusty Rickets', 'Slappy Laszlo', 'Billy the Bass', 'Shiny Pants', 'Bubble Buddy',
  'Alaskan Bull Worm', 'Kevin C. Cucumber', 'Incidental 118', 'Ned', 'Dr. Marmalade', 'Frankie Billy', 'Tom',
  'Eddie the Dolphin', 'Officer Nancy', 'Officer John', 'I am the Law', 'Zapp Brannigan', 'Kif Kroker', 
  'Leela', 'Fry', 'Bender', 'Dr. Zoidberg', 'Professor Farnsworth', 'Amy Wong', 'Hermes Conrad', 
  'Zoidberg', 'Hypnotoad', 'Nibbler', 'Morbo', 'Linda', 'Robot Devil', 'Robot Santa', 'Calculon', 
  'Slurm McKenzie', 'Clamps', 'Tinny Tim', 'Donbot', 'Scruffy', 'Lrrr', 'Nd-Nd', 'Mom', 'Walt', 
  'Larry', 'Igner', 'Hedonismbot', 'Eternal President of Earth', 'God Entity', 'Philip J. Fry', 
  'Turanga Leela', 'Bender Bending Rodriguez'
];
