const OFFENSIVE_WORDS = [
  'nigga', 'nigger', 'n1gger', 'n1gga', 'niggah',
  'faggot', 'fagot',
  'kill yourself', 'kys', 'kill urself',
  'i hate you', 'i hate u',
  'alpha male',
  'heil hitler', 'hail hitler',
  'penis', 'p3nis',
  'vagina', 'v4gina',
  'sex', 's3x',
  'retard', 'r3tard',
  'dyke',
  'tranny', 'trannie',
  'bitch', 'b1tch',
  'bastard',
  'cunt', 'c*nt',
  'whore', 'wh0re',
  'slut',
  'chink',
  'spic', 'spick',
  'wetback',
  'kike',
  'gook',
  'terrorist',
  'raghead', 'rag head',
  'beaner',
  'coon',
  'jihad',
  'nazi',
  'ape',
  'freak',
  'midget', 'midgit',
  'fag',
  'gaylord',
  'paki',
  'mongoloid',
  'redneck', 'red neck',
  'hillbilly', 'hill billy',
  'white trash',
  'uncle tom',
  'sjw', 'social justice warrior',
  'snowflake',
  'libtard',
  'cuck',
  'triggered',
  'autistic', 'autist',
  'spastic',
  'cripple', 'crip',
  'degenerate',
  'invalid',
  'insane', 'in sane',
  'retarded', 'retardid',
  'moron',
  'idiot',
  'stupid', 'stoopid',
  'dumb',
  'fool',
  'foolish',
  'ignorant',
  'pathetic',
  'douchebag', 'douche bag',
  'asshole', 'assh0le',
  'jackass',
  'dickhead', 'dick head',
  'fuck', 'f*ck',
  'shit', 'sh1t',
  'damn',
  'hell',
  'bitch',
  'bimbo',
  'butt monkey',
  'camel jockey',
  'cocksucker', 'cock sucker',
  'cum dumpster', 'cumdumpster',
  'cum guzzler',
  'cum stain', 'cumstain',
  'cumface', 'cum face',
  'cumbubble',
  'cunt licker', 'c*nt licker',
  'dike',
  'dirtbag',
  'dumbass', 'dumb ass',
  'dumbfuck', 'dumb fuck',
  'fagbag',
  'fagfucker', 'fag fucker',
  'faggotry',
  'fatass', 'fat ass',
  'fuck nugget',
  'fuck puppet',
  'fuck trophy',
  'goddamn', 'goddam',
  'goddamnit', 'goddamnit',
  'gook',
  'horseshit', 'horse shit',
  'jerkoff', 'jerk off',
  'jizz guzzler',
  'knobend', 'knob end',
  'kunt',
  'lameass', 'lame ass',
  'lesbo',
  'mothafucka', 'muthafucka',
  'nig nog',
  'niglet',
  'pissface', 'piss face',
  'pisshead', 'piss head',
  'poon',
  'poonani',
  'prick',
  'pussyfucker', 'pussy fucker',
  'pussylicker', 'pussy licker',
  'queef',
  'raghead', 'rag head',
  'rimjob', 'rim job',
  'shitbag', 'shit bag',
  'shitbagger', 'shit bagger',
  'shitfaced', 'shit faced',
  'shithead', 'shit head',
  'shitspitter', 'shit spitter',
  'slutbag', 'slut bag',
  'slutface', 'slut face',
  'smegma',
  'spic', 'spick',
  'spook',
  'tard',
  'twat',
  'twatlips', 'twat lips',
  'wank stain', 'wankstain',
  'wanker',
  'wetback',
  'whorebag', 'whore bag',
  'whorefucker', 'whore fucker',
  'whoreface', 'whore face',
  'wop',
  'yellowman', 'yellow man',
  'yid',
  'zipperhead', 'zipper head',
  'kill yourself', 'kys', 'kill urself', 'go kill yourself',
  'go die', 'godie',
  'i hate you', 'i hate u',
  'shut up bitch', 'shutup bitch', 'stfu bitch',
  'you suck', 'u suck'
];

module.exports = OFFENSIVE_WORDS;