module.exports = [
  'Lounge', 'Study Group', 'Chill Zone', 'Work Room', 'Music Lovers', 'Book Club', 
  'Gamer Zone', 'Art Room', 'Fitness Club', 'Travel Group', 'Cooking Class', 'Tech Talk', 
  'Movie Night', 'Pet Lovers', 'Fashion Room', 'Parenting', 'Health & Wellness', 
  'DIY Projects', 'Photography', 'History Buffs',
  'The Playground', 'Zen Den', 'Meme Central', 'Creative Corner', 'Adventure Club', 
  'Mindfulness Room', 'Science Lab', 'Fantasy World', 'Gardeners Unite', 'Hackers Hub', 
  'Writers Retreat', 'Anime Alley', 'Comics Corner', 'Outdoor Enthusiasts', 'Speed Demons', 
  'Crafters Cove', 'Astro Lounge', 'Underground Lair', 'Meditation Space', 'Karaoke Club', 
  'Trivia Night', 'Puzzle Masters', 'Fitness Freaks', 'Foodies Delight', 'Brewmasters', 
  'Wine Tasting', 'Night Owls', 'Morning Motivation', 'Car Enthusiasts', 'Retro Gamers', 
  'Board Gamers', 'Card Sharks', 'Mystery Solvers', 'Role Players', 'Dungeons & Dragons', 
  'Sci-Fi Fans', 'Fantasy Fandom', 'History Geeks', 'Language Learners', 'Philosophy Cafe', 
  'Debate Room', 'Shutterbugs', 'Nature Lovers', 'Urban Explorers', 'Crypto Corner', 
  'Stock Traders', 'Investors Club', 'Real Estate', 'Startups', 'Entrepreneurs', 
  'Small Business', 'Marketing Gurus', 'Public Speakers', 'Life Coaches', 'Spiritual Seekers', 
  'Yoga Studio', 'Pilates Room', 'Dance Hall', 'Martial Artists', 'Survivalists', 
  'Home Improvement', 'Interior Design', 'Minimalists', 'Collectors', 'Antique Lovers', 
  'Toy Enthusiasts', 'Model Makers', 'RC Hobbyists', 'Stamp Collectors', 'Coin Collectors', 
  'Action Figures', 'Dollhouse', 'Miniatures', 'Handmade Crafts', 'Knitting Circle', 
  'Quilters', 'Sewing Room', 'Embroidery', 'Beadwork', 'Scrapbooking', 'Origami', 
  'Jewelry Making', 'Pottery Studio', 'Woodworking', 'Metalworking', 'Glassblowing', 
  'Leathercraft', 'Blacksmithing', 'Calligraphy', 'Graphic Design', 'Web Developers', 
  'App Developers', 'Tech Support', 'Gadget Geeks', 'PC Builders', 'VR Enthusiasts', 
  'AR Innovators', 'AI Enthusiasts', 'Robot Builders', 'Drone Pilots', '3D Printing', 
  'Makerspace', 'Innovation Hub', 'Think Tank', 'Research Lab', 'Space Explorers', 
  'Astronomy Club', 'Astrophotography', 'Rocketry', 'UFO Sightings', 'Paranormal', 
  'Ghost Hunters', 'Myth Busters', 'Conspiracy Theories', 'True Crime', 'Detectives', 
  'Forensics', 'Law & Order', 'Civil Rights', 'Environmentalists', 'Animal Rights', 
  'Human Rights', 'Activists', 'Political Debate', 'Elections', 'Global Affairs', 
  'United Nations', 'World Health', 'Peacekeepers', 'Disaster Relief', 'Volunteers', 
  'Community Service', 'Neighborhood Watch', 'Local News', 'Breaking News', 'Weather Watchers', 
  'Storm Chasers', 'Astronomy', 'Climate Change', 'Sustainability', 'Eco Warriors', 
  'Zero Waste', 'Recycling', 'Upcycling', 'Permaculture', 'Organic Gardening', 
  'Hydroponics', 'Aquaponics', 'Vertical Farming', 'Urban Farming', 'Homesteading', 
  'Tiny Homes', 'Van Life', 'RV Living', 'Boat Life', 'Island Living', 'Mountain Retreats', 
  'Beach Bums', 'Desert Dwellers', 'City Slickers', 'Country Living', 'Suburban Life', 
  'Off Grid', 'Grid Tied', 'Smart Homes', 'Home Theater', 'Man Cave', 'She Shed', 
  'Family Room', 'Kids Zone', 'Teen Hangout', 'Senior Space', 'Pet Playroom', 'Dog Park', 
  'Cat Cafe', 'Bird Aviary', 'Reptile Room', 'Aquarium', 'Fish Tank', 'Pet Hospital', 
  'Vet Clinic', 'Adoption Center', 'Animal Rescue', 'Farm Sanctuary'
];
